Initialize project
neofinancial/graphql-date-scalars pull request #1
Opened 2020-10-17 22:33 UTC by MarkPolivchuk

conforming to configs for other open source projects

2020-10-17 22:50 UTC, iansu requested changes

2020-10-17 22:50 UTC, iansu commented on .eslintignore
> +dist
I don't think we have `dist` in this project.

2020-10-17 22:50 UTC, iansu commented on .eslintrc
> +    "no-console": "off",
Are these rule customizations needed?

2020-10-17 22:50 UTC, iansu commented on .prettierrc
> +  "printWidth": 100,
This should be 120.

2020-10-17 22:50 UTC, iansu commented on README.md
> +Graphql Scalars for Date (YYYY-MM-DD), DateTime (YYYY-MM-DDTHH:MM:SSZ), and Time (HH:MM:SSZ)
```suggestion
GraphQL Scalars for Date (YYYY-MM-DD), DateTime (YYYY-MM-DDTHH:MM:SSZ), and Time (HH:MM:SSZ)
```

2020-10-17 22:50 UTC, iansu commented on package.json
> +  "version": "1.1.1",
You should change this to `1.0.0` or `0.1.0`

2020-10-17 22:50 UTC, iansu commented on package.json
> +    "node": ">=10.0.0"
Let's use Node 12 as the minimum version.

2020-10-17 22:50 UTC, iansu commented on package.json
> +    "build": "NODE_ENV=production ncc build src/app.ts -o build --minify --external update-notifier",
We don't want to use ncc in this project.

2020-10-17 22:50 UTC, iansu commented on package.json
> +    "typescript": "3.7.5"
Make sure to bump all the dependencies.

2020-10-18 23:01 UTC, iansu requested changes

2020-10-18 23:01 UTC, iansu commented on package.json
> +    "prettier": "2.1.2",
Our ESLint config doesn't currently work with Prettier 2 or TypeScript 4.

2020-11-11 21:11 UTC, iansu requested changes

2020-11-11 21:11 UTC, iansu commented on LICENSE
> +Copyright (c) 2020 Neo Financial Technologies Inc., Dirk-Jan Rutten
```suggestion
Copyright (c) 2020 Neo Financial Technologies Inc.
Copyright (c) 2017 Dirk-Jan Rutten
```

2020-11-11 21:12 UTC, iansu commented on LICENSE
> +Copyright (c) 2020 Neo Financial Technologies Inc., Dirk-Jan Rutten
I don't actually know the correct way to do this but some Googling resulted in this.

2020-11-12 17:27 UTC, krisread commented
@iansu  @MarkPolivchuk   Hey why is this blocked, is this worth keeping open, its 20+ days old, is there a major issue...?  It looks like the last suggestion was not worth blocking over?

2020-11-12 17:29 UTC, iansu commented
I do think getting the license correct is important. That's the only remaining change.

2020-11-12 17:38 UTC, iansu approved these changes

2020-11-12 17:44 UTC, merged